---
- name: Cleanup Dynamic Inventory
  hosts: localhost
  gather_facts: false

  vars:
    inventory_name: Dynamic_Inventory

  tasks:

    - name: Bulk delete dynamic hosts
      ansible.controller.bulk_host_delete:
        inventory: "{{ inventory_name }}"
        hosts: "{{ cleanup_hosts }}"
