---
- name: Cleanup Dynamic Inventory
  hosts: localhost
  gather_facts: false

  vars:
    inventory_name: Dynamic_Inventory

  tasks:

    - name: Get hosts from inventory
      ansible.controller.host_list:
        inventory: "{{ inventory_name }}"
      register: host_list

    - name: Delete all hosts
      ansible.controller.host:
        inventory: "{{ inventory_name }}"
        name: "{{ item.name }}"
        state: absent
      loop: "{{ host_list.hosts }}"
