---
- name: Register host and launch job
  hosts: localhost
  gather_facts: false

  vars:
    inventory_name: Dynamic_Inventory
    target_job_template: Linux Patch Job

  tasks:
    - name: To print the targetIP
      ansible.builtin.debug:
        var: target_ip

    - name: To print the inventory name
      ansible.builtin.debug:
        var: inventory_name
    
    - name: Create host
      ansible.controller.host:
        inventory: "{{ inventory_name }}"
        name: "{{ target_ip }}"
        variables:
          ansible_host: "{{ target_ip }}"
        state: present
        request_timeout: 30

